### ISSUE TITLE
Duplicate: Sidebar Overflow issue

### ISSUE THREAD

**Issue by QuickHarsh** [whtrapp/whtrapp.github.io#10]
by scrolling down on the website the background is not showing properly as you see in the below image.
so kindly assign me so that i can fix this issue.

![weather github](https://github.com/user-attachments/assets/7f187cef-bcab-4bc4-b1c0-d767fb6103f5)

**Comment by AalokeCode** [comment]
Hey! This is a duplicate of the issue #5

**Comment by QuickHarsh** [comment]
ok i will....
