### ISSUE TITLE
Enhancement: Adding autocomplete feature for search bar.

### ISSUE THREAD

**Issue by aldrin312** [whtrapp/whtrapp.github.io#18]
Adding an autocomplete feature can maybe quicken to search for a particular city.

![image](https://github.com/user-attachments/assets/ccfe8f0e-b4dd-484e-a0f9-f2058e3606a8)

Can I get assigned for this for hacktoberfest?

**Comment by Anurag-singh-thakur** [comment]
@AalokeCode can i work on that ?

**Comment by AalokeCode** [comment]
Hey @Anurag-singh-thakur! Since @aldrin312 mentioned about the issue and requested to work on it first, I'm assigning this to him. But feel free to share any ideas or suggestions, as we are always open to collaboration.
