### ISSUE TITLE
Enhancement: Beautifying the Scrollbar near the sidebar

### ISSUE THREAD

**Issue by AalokeCode** [whtrapp/whtrapp.github.io#23]
![image](https://github.com/user-attachments/assets/23fc22bd-d538-4118-8373-c8447684bcd7)
<br />
The Scrollbar near the sidebar can be beautified using CSS. Anyone interested can let me know. I'll assign the issue!

**Comment by Priyanshu-su30** [comment]
I am interested Assign me this

**Comment by rdgl** [comment]
@AalokeCode 
Please assign this issue to me I would like to solve it

**Comment by shiv-0101** [comment]
Hey @AalokeCode to beautify it, do you mean to add colors, border (something that look catchy?)

If it's that, would love to code it.

**Comment by AalokeCode** [comment]
Hey @rdgl and @shiv-0101! I've listed some more bugs that you can work on.

**Comment by Priyanshu-su30** [comment]
Wasn't I supposed to work on this??

**Comment by AalokeCode** [comment]
Hey @Priyanshu-su30 Apologies. I've assigned you another issue that you can work on

**Comment by shiv-0101** [comment]
Closed!!
