### ISSUE TITLE
Bug: Last visited also saves non-cities when searched up

### ISSUE THREAD

**Issue by AalokeCode** [whtrapp/whtrapp.github.io#25]
![image](https://github.com/user-attachments/assets/d08863cd-bc32-4458-a6a4-dc9459585eba)
<br>
Please let me know if anyone wants to fix this issue!

**Comment by StrangeAJ** [comment]
Hey @AalokeCode ,

I have fixed this issue along with scrollbar UI design. Here in this [Pull Request].(https://github.com/whtrapp/whtrapp.github.io/pull/28#issue-2611417343)
