### ISSUE TITLE
Enhancement: Improving Homepage with Title and Typing Effect

### ISSUE THREAD

**Issue by vivek-anand-singh** [whtrapp/whtrapp.github.io#31]
### Description
We would like to enhance the homepage by adding a title, a typing effect for dynamic text, and a description that captures the essence of our service. The typing effect should specifically display the name of a city to engage users effectively.

### Requirements
1. **Add a Title**: 
   - The title should be prominently displayed at the top of the homepage.

2. **Add a Typing Effect**:
   - Implement a typing effect for the city name, making it visually appealing and interactive.
   - The effect should simulate typing the city name on the screen, pausing briefly between letters.

3. **Add a Description**:
   - A brief description below the title that outlines what our service offers.

4. **Dynamic City Name Display**:
   - Create a placeholder for the city name that will be animated with the typing effect.

### Additional Notes
- Consider adding styling to enhance the visual appeal of the title and description.
- Review the typing effect speed to ensure it feels natural.

**Comment by vivek-anand-singh** [comment]
I would like to work on this issue could you please assign this issue to me

@AalokeCode

**Comment by AalokeCode** [comment]
Hmm Interesting. Alright you can work on it!

**Comment by vivek-anand-singh** [comment]
Hi @AalokeCode! I've made the requested changes. Please review and let me know if there's anything else you'd like adjusted. Thanks
