### ISSUE TITLE
Enhancement: Change background as per time

### ISSUE THREAD

**Issue by dharshini2022** [whtrapp/whtrapp.github.io#38]
**Current Feature:**
The current background is static

![{DFE53F81-BC76-4005-A959-8ED69F08DDC5}](https://github.com/user-attachments/assets/23b54796-a0d4-49e7-a0b8-88b8f849300b)

**Enhancements:**
Change the background as per the time of the selected city

Pls assign me this issue under Hacktoberfest

**Comment by AalokeCode** [comment]
Alright! You can work on it

**Comment by MrTanoshii** [comment]
This doesn't seem to be worked on so I made a PR
