### ISSUE TITLE
Enhancement: Improving the PageSpeed Insights

### ISSUE THREAD

**Issue by AalokeCode** [whtrapp/whtrapp.github.io#42]
Improving the Performance and Accessibility to achieve max score! Anyone interested? If so let me know, I'll assign the issue
<img width="981" alt="Screenshot 2024-10-26 at 7 15 18 PM" src="https://github.com/user-attachments/assets/2838ba6f-8664-4600-85fa-a11e630e3eb3">

**Comment by Macvncpro** [comment]
Hi, 

    I would like to give this a go, do you have any specific designs in mind or are we free to improve it in anyway possible.

**Comment by AalokeCode** [comment]
Hey @Macvncpro! Just keep the code intact. Only change stuff if required to the accessibility.

**Comment by Macvncpro** [comment]
Hi , 
     I cannot do this because of lack of experience. Sorry for any inconvenience.

**Comment by AalokeCode** [comment]
Alright! No worries.

**Comment by atinder-harika** [comment]
I would love to work on increasing the accessibility score, I have done so for my previous web games. @AalokeCode Kindly assign me this issue I will solve this in a few days.

**Comment by AalokeCode** [comment]
Hey @atinder-harika! I'll assign you the issue.

**Comment by atinder-harika** [comment]
@AalokeCode I have opened the pull request. Kindly review it before October ends.

**Comment by atinder-harika** [comment]
@AalokeCode I know its kinda early in India but if possible can you approve this within 2 hours? I really want to get my 4th pr in for hacktober
