### ISSUE TITLE
Enhancement: Repositioning the Explore Button to a better place

### ISSUE THREAD

**Issue by AalokeCode** [whtrapp/whtrapp.github.io#43]
Currently the explore button seems to be displaced which tends to distract the experience a bit. So this issue should 
1. Reposition the button
2. Can add further enhancements to the button to make it better

<img width="1510" alt="Screenshot 2024-10-26 at 7 21 23 PM" src="https://github.com/user-attachments/assets/c9220490-9d0b-4483-bc96-7f0867e1381c">

**Comment by Malay-dev** [comment]
Hey Can I work on this issue?

**Comment by AalokeCode** [comment]
Hey @Malay-dev! Sure you can work on it.

**Comment by Malay-dev** [comment]
![image](https://github.com/user-attachments/assets/fb2f2b52-9bb1-44c7-af50-65ca2ec1a8b6)

@AalokeCode How about this look? Or if there is any preference...

**Comment by AalokeCode** [comment]
Thats a very cool one! But do you think the sidebar is congested? Like too many elements in the sidebar?

**Comment by Malay-dev** [comment]
I don't think the sidebar is congested. It's the only navigation menu we have.

**Comment by kushaltalati** [comment]
@AalokeCode I can try updating it, assign me with this task under hactoberfest tag.

**Comment by AalokeCode** [comment]
Hey @kushaltalati. I've already assigned this issue to @Malay-dev. I'll be finding some more issues/enhancements and putting them up in few hours. I'll mention you there if you want.
