### ISSUE TITLE
Enhancement: Fix  Sidebar overflow issue

### ISSUE THREAD

**Issue by AbdurrahmanSogbesan** [whtrapp/whtrapp.github.io#5]
I noticed some blank space while looking at the app, and i believe it could be fixed by fixing the overflow issue of the sidebar. Please assign this to me with the hacktoberfest label

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/191f4faa-0168-43c7-a55f-7df97976008b">

**Comment by AalokeCode** [comment]
Aight! Have at it.
